[workspace]
members = ["sniffer-extcap", "wire-format"]
exclude = ["esp-fw", "nrf-fw"]
resolver = "2"

[workspace.dependencies]
postcard = { version = "1.0" }
serde = { version = "1.0", default-features = false }
heapless = { version = "0.8.0", features = ["serde"] }
